# Testing some Pytorch activations functions

In [2]:
import torch
import torch.nn.functional as F

# Create a sample input tensor
x = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0])

x

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
torch.sigmoid(x)


tensor([0.1192, 0.2689, 0.5000, 0.7311, 0.8808])

In [4]:
torch.tanh(x)

tensor([-0.9640, -0.7616,  0.0000,  0.7616,  0.9640])

In [5]:
F.relu(x)

tensor([0., 0., 0., 1., 2.])

In [6]:
F.leaky_relu(x, negative_slope=0.01)

tensor([-0.0200, -0.0100,  0.0000,  1.0000,  2.0000])

In [9]:
prelu = torch.nn.PReLU(num_parameters=1, init=0.25)
prelu(x)

tensor([-0.5000, -0.2500,  0.0000,  1.0000,  2.0000],
       grad_fn=<PreluKernelBackward0>)

In [10]:
F.elu(x, alpha=1.0)

tensor([-0.8647, -0.6321,  0.0000,  1.0000,  2.0000])

In [11]:
x * torch.sigmoid(x)

tensor([-0.2384, -0.2689,  0.0000,  0.7311,  1.7616])

In [12]:
F.softmax(x, dim=0)

tensor([0.0117, 0.0317, 0.0861, 0.2341, 0.6364])